FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-golang:1.19-3.16-build as build

RUN mkdir /build/
WORKDIR /build/

ADD . .

RUN go build
RUN ls -la

FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine:3.16 as run

ENV UDEV=1

RUN mkdir /fakeSungrowMeter
WORKDIR /fakeSungrowMeter
COPY --from=build /build/fakeSungrowMeter .

CMD ["/fakeSungrowMeter/fakeSungrowMeter"]



